# Generated by Django 2.0.2 on 2020-02-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Disciplines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
